config = {
    GAME_STATE = "play",
    MAX_FRAME = 100,
    MIN_SHOOT_DELAY = 1,
    MAX_SHOOT_DELAY = 3,
    MESSAGE_Y = 50,
    PLAYER_COOLDOWN = 100,
    ENEMY_VERTICAL_MOVE = 15,
    ENEMY_HORIZONTAL_MOVE = 10,
    STAR_COUNT = 500
}
